### ISSUE TITLE
texteditor module not compiling withi PyInstaller

### ISSUE THREAD

**Issue by shift838** [jpsca/texteditor#4]
I can compile a simple program (see below) which calls the texteditor module succesfully.  but upon launching the executable I get the error shown although the source runs with no issues before compile.

`#!/usr/bin/python3

import texteditor
text = texteditor.open(filename = 'readme.md')`

When running the executable on my windows 10 machine the below errors are displayed:

Traceback (most recent call last):
  File "texted.py", line 3, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "c:\users\cvsch\appdata\local\programs\python\python39\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
    exec(bytecode, module.__dict__)
  File "texteditor\__init__.py", line 2, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "c:\users\cvsch\appdata\local\programs\python\python39\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
    exec(bytecode, module.__dict__)
  File "texteditor\version.py", line 4, in <module>
  File "pkg_resources\__init__.py", line 899, in require
  File "pkg_resources\__init__.py", line 785, in resolve
pkg_resources.DistributionNotFound: The 'text-editor' distribution was not found and is required by the application
[21060] Failed to execute script texted

a 'pip list' does show the required package is installed.

C:\Users\cvsch\Documents\pyqtprojects\oog4b201018-2200\dist\texted>pip list
Package                   Version
------------------------- ---------
altgraph                  0.17
beautifulsoup4            4.9.3
bs4                       0.0.1
desktop-file              1.2
future                    0.18.2
iso8601                   0.1.13
pefile                    2019.4.18
pip                       20.2.4
py2exe                    0.9.2.2
pyinstaller               4.0
pyinstaller-hooks-contrib 2020.9
pypiwin32                 223
PyQt5                     5.15.1
PyQt5-sip                 12.8.1
PyQt5Designer             5.14.1
pyserial                  3.4
pywin32                   228
pywin32-ctypes            0.2.0
PyYAML                    5.3.1
serial                    0.0.97
setuptools                49.2.1
soupsieve                 2.0.1
text-editor               1.0.5

**Comment by jpsca** [comment]
"text-editor" (with an hyphen) was an old, temporary name of the package. The name is now "**texteditor**" (without the hyphen).

Please update your requirements to use the "texteditor" instead https://pypi.org/project/texteditor/
I will remove the old package from pypi to avoid further confusion.
